# Generated by Django 6.0.7 on 2026-07-08 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase_id', models.CharField(max_length=100)),
                ('testcase_name', models.CharField(max_length=255)),
                ('parameters', models.TextField(blank=True)),
                ('parameters_raw', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('test_step_description', models.TextField(blank=True)),
                ('test_step_status', models.CharField(blank=True, max_length=20)),
                ('expected_result', models.TextField(blank=True)),
                ('actual_result', models.TextField(blank=True)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('tester_conclusion', models.TextField(blank=True)),
                ('analysis_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Analyzed', 'Analyzed'), ('Issue Confirmed', 'Issue Confirmed'), ('False Alarm', 'False Alarm'), ('Closed', 'Closed')], default='Not Started', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='reports.execution')),
            ],
        ),
    ]
