# Generated by Django 6.0.7 on 2026-07-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('key', models.CharField(help_text='External ticket key, e.g., JIRA-123', max_length=100, unique=True)),
                ('url', models.URLField(blank=True, help_text='Link to the ticket in the tracking system')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['execution_id', 'testcase_id']},
        ),
        migrations.AddField(
            model_name='execution',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this execution run'),
        ),
        migrations.AddField(
            model_name='execution',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='reports.ticket'),
        ),
    ]
