# Generated by Django 6.0.7 on 2026-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_execution_uploaded_by_ticket_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='manager_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Tester', 'Tester'), ('Manager', 'Manager')], default='Tester', max_length=20),
        ),
    ]
